name: CI/CD Pipeline for Flask API

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: python -m unittest discover tests/

      - name: Build Docker image (optional)
        run: |
          docker build -t my-flask-api .

      - name: Deploy to Cloud (example for GCP)
        run: |
          gcloud auth activate-service-account --key-file=${{ secrets.GCP_SA_KEY }}
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud run deploy my-flask-api --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/my-flask-api --platform managed --region us-central1 --allow-unauthenticated
